### ISSUE TITLE
Getting any error in getoffset

### ISSUE THREAD

**Issue by suryapraneeta** [LukeAllen/optimeyes#8]
Hi, I am using Python 3.6.5
While am running the code I am getting the below error. Tried to change the that float value in the getoffset function but still am Getting that error please help me in debugging.

Traceback (most recent call last):
  File "E:\praneeta\eye gaze\optimeyes-master\optimeyes-master\eyeDetect.py", line 726, in <module>
    main()
  File "E:\praneeta\eye gaze\optimeyes-master\optimeyes-master\eyeDetect.py", line 656, in main
    pupilOffsetXYList = getOffset(frame, allowDebugDisplay=True)
  File "E:\praneeta\eye gaze\optimeyes-master\optimeyes-master\eyeDetect.py", line 474, in getOffset
    cv2.circle(output, pupilXYList[eyeIndex], 3, (255,0,0),thickness=1) #BGR format
TypeError: integer argument expected, got float

**Comment by LukeAllen** [comment]
Hey, the code is only compatible with Python 2.7 right now. I'm probably not going to work on Python 3 conversion in the near future, but if you add Python 3 compatibility and submit a pull request I would review it.

**Comment by suryapraneeta** [comment]
Hi

Can you please tell me how to do this eye detection for multiple faces.

Kindly please help me in developing.
